<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheeltec_robot">

  <!-- ============================================================ -->
  <!-- 机器人参数定义 -->
  <!-- TODO: 请根据实际机器人尺寸修改以下参数 -->
  <!-- ============================================================ -->
  
  <!-- 底盘尺寸 -->
  <xacro:property name="base_length" value="0.50"/>    <!-- 底盘长度 (m) -->
  <xacro:property name="base_width" value="0.43"/>     <!-- 底盘宽度 (m) -->
  <xacro:property name="base_height" value="0.15"/>    <!-- 底盘高度 (m) -->
  
  <!-- 轮子参数 (根据 robot_params.hpp 更新) -->
  <xacro:property name="wheel_radius" value="0.075"/>  <!-- 轮子半径 (m) = 直径0.15/2 -->
  <xacro:property name="wheel_width" value="0.06"/>    <!-- 轮子宽度 (m) -->
  <xacro:property name="wheel_separation" value="0.50"/>  <!-- 轮距 (m) -->
  <xacro:property name="wheel_base" value="0.43"/>     <!-- 轴距 (m) -->
  
  <!-- 激光雷达安装位置（相对于base_link） -->
  <xacro:property name="lidar_x" value="-0.20"/>       <!-- X方向偏移 (m) 向后20cm -->
  <xacro:property name="lidar_y" value="-0.05"/>       <!-- Y方向偏移 (m) 向右5cm -->
  <xacro:property name="lidar_z" value="0.25"/>        <!-- Z方向偏移 (m) -->
  
  <!-- IMU安装位置（相对于base_link） -->
  <xacro:property name="imu_x" value="0.0"/>
  <xacro:property name="imu_y" value="0.0"/>
  <xacro:property name="imu_z" value="0.075"/>

  <!-- ============================================================ -->
  <!-- 材质定义 -->
  <!-- ============================================================ -->
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>
  
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.2 0.2 1"/>
  </material>
  
  <material name="green">
    <color rgba="0.2 0.8 0.2 1"/>
  </material>

  <!-- ============================================================ -->
  <!-- base_footprint - 地面投影坐标系 -->
  <!-- ============================================================ -->
  
  <link name="base_footprint"/>
  
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ============================================================ -->
  <!-- base_link - 机器人主体 -->
  <!-- ============================================================ -->
  
  <link name="base_link">
    <visual>
      <!-- 使用 STL 模型文件 -->
      <!-- 注意: scale="0.001" 表示 STL 单位是 mm，转换为 m -->
      <!-- Z 轴偏移 +0.075m，绕 Z 轴旋转 90 度 (pi/2 = 1.5708 rad) -->
      <origin xyz="0 0 0.075" rpy="0 0 1.5708"/>
      <geometry>
        <mesh filename="package://wheeltec_description/meshes/model3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <!-- 碰撞使用简化的盒子模型，提高性能 -->
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="10.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- ============================================================ -->
  <!-- 轮子宏定义 -->
  <!-- ============================================================ -->
  
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_wheel_link">
      <!-- 不显示轮子视觉模型，因为 STL 模型已经包含轮子 -->
      <!-- 只保留碰撞和惯性属性用于物理仿真 -->
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
    
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_reflect * wheel_base/2} ${y_reflect * wheel_separation/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- 四个麦克纳姆轮 -->
  <xacro:wheel prefix="front_left" x_reflect="1" y_reflect="1"/>
  <xacro:wheel prefix="front_right" x_reflect="1" y_reflect="-1"/>
  <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1"/>

  <!-- ============================================================ -->
  <!-- laser_frame - 激光雷达坐标系 -->
  <!-- ============================================================ -->
  
  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.06"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.06"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.3"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="${lidar_x} ${lidar_y} ${lidar_z}" rpy="0 0 0"/>
  </joint>

  <!-- ============================================================ -->
  <!-- imu_link - IMU坐标系 -->
  <!-- ============================================================ -->
  
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>
  
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0 0 0"/>
  </joint>

</robot>
