<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheeltec_robot">

  <!-- ============================================================ -->
  <!-- 机器人参数定义 -->
  <!-- TODO: 请根据实际机器人尺寸修改以下参数 -->
  <!-- ============================================================ -->
  
  <!-- 底盘尺寸 -->
  <xacro:property name="base_length" value="0.30"/>    <!-- 底盘长度 (m) -->
  <xacro:property name="base_width" value="0.26"/>     <!-- 底盘宽度 (m) -->
  <xacro:property name="base_height" value="0.10"/>    <!-- 底盘高度 (m) -->
  
  <!-- 轮子参数 -->
  <xacro:property name="wheel_radius" value="0.05"/>   <!-- 轮子半径 (m) -->
  <xacro:property name="wheel_width" value="0.04"/>    <!-- 轮子宽度 (m) -->
  <xacro:property name="wheel_separation" value="0.30"/>  <!-- 轮距 (m) -->
  <xacro:property name="wheel_base" value="0.25"/>     <!-- 轴距 (m) -->
  
  <!-- 激光雷达安装位置（相对于base_link） -->
  <!-- TODO: 根据实际安装位置修改 -->
  <xacro:property name="lidar_x" value="0.0"/>         <!-- X方向偏移 (m) -->
  <xacro:property name="lidar_y" value="0.0"/>         <!-- Y方向偏移 (m) -->
  <xacro:property name="lidar_z" value="0.20"/>        <!-- Z方向偏移 (m) -->
  
  <!-- IMU安装位置（相对于base_link） -->
  <xacro:property name="imu_x" value="0.0"/>
  <xacro:property name="imu_y" value="0.0"/>
  <xacro:property name="imu_z" value="0.05"/>

  <!-- ============================================================ -->
  <!-- 材质定义 -->
  <!-- ============================================================ -->
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>
  
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.2 0.2 1"/>
  </material>

  <!-- ============================================================ -->
  <!-- base_footprint - 地面投影坐标系 -->
  <!-- ============================================================ -->
  
  <link name="base_footprint"/>
  
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ============================================================ -->
  <!-- base_link - 机器人主体 -->
  <!-- ============================================================ -->
  
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.05" iyz="0" izz="0.05"/>
    </inertial>
  </link>

  <!-- ============================================================ -->
  <!-- 轮子宏定义 -->
  <!-- ============================================================ -->
  
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
    
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_reflect * wheel_base/2} ${y_reflect * wheel_separation/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- 四个麦克纳姆轮 -->
  <xacro:wheel prefix="front_left" x_reflect="1" y_reflect="1"/>
  <xacro:wheel prefix="front_right" x_reflect="1" y_reflect="-1"/>
  <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1"/>

  <!-- ============================================================ -->
  <!-- laser_frame - 激光雷达坐标系 -->
  <!-- ============================================================ -->
  
  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.06"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.06"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.3"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="${lidar_x} ${lidar_y} ${lidar_z}" rpy="0 0 0"/>
  </joint>

  <!-- ============================================================ -->
  <!-- imu_link - IMU坐标系 -->
  <!-- ============================================================ -->
  
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>
  
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0 0 0"/>
  </joint>

</robot>
